#spring.datasource.url=jdbc:mysql://localhost:3306/authentication_db
#spring.datasource.username=root
#spring.datasource.password=Sahasiem7#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db?createDatabaseIfNotExist=true
    username: root
    password: welcome@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect