#spring.datasource.url=jdbc:mysql://localhost:3306/authentication_db
#spring.datasource.username=root
#spring.datasource.password=Sahasiem7#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db?createDatabaseIfNotExist=true
    username: root
    password: Sahasiem7#
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: swapnilsutar2221@gmail.com
    password: uddtggyiaggetsmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 527418272190193
            clientSecret: 415484f110314b296e69d151d3caf91f
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            resource:
              userInfoUri: https://graph.facebook.com/me